cloud:
  aws:
    credentials:
      access-key: your_access_key
      secret-key: your_secret_key
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  bucket:
    name: kainen-bucket


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

server:
  port: 8080